# Site settings
title: "Oliveira e Alves Advocacia | Assessoria Jurídica"
description: "Oliveira e Alves Advocacia | Assessoria Jurídica"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.png

# Hero
hero:
    hero_img: hero.jpg
    hero_title: Oliveira e Alves Advocacia
    hero_description: "Assessoria Jurídica"

# Contact form
api_token: b1291c072b839b5d24d741827cf930ee # Enter API token here

# Contact info
contact:
    phone: (11) 4138-5220
    whatsapp: 5511986882944
    email: contato@oliveiraealvesadvocacia.com.br
    address_line1: "Estr. Kizaemon Takeuti, nº 2487, Conj. 3"
    address_line2: "Pq. São Joaquim, Taboão da Serra/SP"
    address_line3: "CEP 06775-003"
    address_line4: "Próximo ao PoupaTempo"

# Opening hours
monday_friday: "9:00 às 12:00 e 13:00 às 18:00"
#saturday: 10:00 – 17:00
#sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Social settings
facebook: https://www.facebook.com/Oliveira-Alves-Advocacia-111089440750561/
twitter: https://twitter.com/OliveiraAlvesA2
instagram: https://www.instagram.com/oliveiraealvesadvocacia/
youtube: https://www.youtube.com/channel/UCKEmedjENq6KfUKG2NbUS0w/
whatsapp: 5511986882944
skype:
feed: no

# Footer
copyright: © Oliveira e Alves Advocacia - Todos os direitos reservados

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics:
google_verification:
